`timescale 1ns/10ps
// insipred by myipp_v1_0_S00_AXIS generated by AMD's Vivado'create custom IP code
module avl2axi #
	(
		// Users to add parameters here
		parameter integer FACTOR = 2,
		// User parameters ends
		// Do not modify the parameters beyond this line

		// AXI4Stream source: Data Width
		parameter integer DATA_WIDTH	= 16,
		parameter integer NUM_OF_SAMPLES = 2000 
	)
	(
		// Avalon st tx port
		//! indicates if the connected Avalon-ST sink interface accepts data
		output reg DATA_OUTPUT_READY,
		//! the transaction is valid		
		input wire DATA_OUTPUT_VALID,
		//! signals a sink that a new packet will be sent		
		input wire DATA_OUTPUT_STARTOFPACKET,
		//! signals the end of a packet		
		input wire DATA_OUTPUT_ENDOFPACKET,
		//! transaction data		
		input wire [DATA_WIDTH-1:0] DATA_OUTPUT_DATA,	

		// AXI4Stream source: Clock
		input wire  M_AXIS_ACLK,
		// AXI4Stream source: Reset
		input wire  M_AXIS_ARESETN,
		// Ready to accept data out
		input wire  M_AXIS_TREADY,
		// Data out
		output reg [DATA_WIDTH-1:0] M_AXIS_TDATA,
		// Indicates boundary of last packet
		output reg  M_AXIS_TLAST,
		// Data is output valid
		output reg  M_AXIS_TVALID
	);
	// function called clogb2 that returns an integer which has the 
	// value of the ceiling of the log base 2.
	function integer clogb2 (input integer bit_depth);
	  begin
	    for(clogb2=0; bit_depth>0; clogb2=clogb2+1)
	      bit_depth = bit_depth >> 1;
	  end
	endfunction

	// Total number of input data.
	localparam NUMBER_OF_OUTPUT_WORDS  = NUM_OF_SAMPLES/FACTOR; // output packet number includes 3 words of header and 1 error word
	// bit_num gives the minimum number of bits needed to address 'NUMBER_OF_OUTPUT_WORDS' size of FIFO.
	localparam bit_num  = clogb2(NUMBER_OF_OUTPUT_WORDS-1);
	// Define the states of state machine
	// The control state machine oversees the writing of input streaming data to the FIFO,
	// and outputs the streaming data from the FIFO
	parameter [1:0] IDLE = 1'b0,        // This is the initial/idle state 

	                WRITE_FIFO  = 1'b1; // In this state FIFO is written with the
	                                    // input stream data M_AXIS_TDATA 
	// Triggers start of read FIFO
	wire fifo_almost_full;
	// Triggers start of write FIFO
	wire avl_output_ready;
	// State variable
	reg mst_exec_state;     
	// FIFO write enable
	wire fifo_wren;
	// start of frame for avalon st rx
	reg start_of_frame;
	// end of frame for avalong st rx
	reg end_of_frame;
	// FIFO write pointer
	reg [bit_num-1:0] write_pointer;
	// sink has accepted all the streaming data and stored in FIFO
	reg writes_done; 	
	// FIFO read pointer
	reg [bit_num-1:0] read_pointer;
	// sink has emptied all the streaming data and from FIFO
	reg reads_done;
	// ack and clears reads_done
	reg reads_done_ack; 	

	assign DATA_OUTPUT_READY	= avl_output_ready;
	
	// Control state machine implementation
	always @(posedge M_AXIS_ACLK or negedge M_AXIS_ARESETN) 
	begin  
	  if (!M_AXIS_ARESETN) 
	  // asynchronous reset (active low)
	    begin
	      mst_exec_state <= IDLE;
	    end  
	  else
	    case (mst_exec_state)
	      IDLE: 
	        // The source starts accepting avl data when 
	        // DATA_OUTPUT_STARTOFPACKET is asserted to mark the
	        // beginning of data 
	          if (DATA_OUTPUT_STARTOFPACKET)
	            begin
	              mst_exec_state <= WRITE_FIFO;
	            end
	          else
	            begin
	              mst_exec_state <= IDLE;
	            end
	      WRITE_FIFO: 
	        // When the source has accepted all the streaming output data,
	        // the interface swiches functionality to a sourcing slave
	        if (DATA_OUTPUT_ENDOFPACKET)
	          begin
	            mst_exec_state <= IDLE;
	          end
	        else
	          begin
	            // The source accepts and stores tdata 
	            // into FIFO
	            mst_exec_state <= WRITE_FIFO;
	          end

	    endcase
	end
	// AXI Streaming Source 
	// 
	// The example design source is ready to send the M_AXIS_TDATA when
	// the FIFO is filled with NUMBER_OF_OUTPUT_WORDS number of output words.
	//assign avl_output_ready = ((mst_exec_state == WRITE_FIFO) && (write_pointer <= NUMBER_OF_OUTPUT_WORDS-1));
	// fir_avl require FIFO to be ready to start convolution so don't wait to enter WRITE_FIFO state otherwise will deadlock
	assign avl_output_ready = ((write_pointer <= NUMBER_OF_OUTPUT_WORDS-1) && !read_pointer); // cannot write until previous read is done
	// almost full flag as a pulse to trigger read, read is same speed as write, every second clock there is a write transcation after 3 words of header
	assign fifo_almost_full = (write_pointer == NUMBER_OF_OUTPUT_WORDS-1);  // read only when write is done
	
	always@(posedge M_AXIS_ACLK or negedge M_AXIS_ARESETN) 
	begin
	  if(!M_AXIS_ARESETN)
	    begin
	      write_pointer <= 0;
	      writes_done <= '0;
	    end  
	  else
	    if (write_pointer <= NUMBER_OF_OUTPUT_WORDS-1)
	      begin
	        if (fifo_wren)
	          begin
				if ((write_pointer == NUMBER_OF_OUTPUT_WORDS-1)|| DATA_OUTPUT_ENDOFPACKET)
				begin
	              // reads_done is asserted when NUMBER_OF_OUTPUT_WORDS numbers of streaming data 
	              // has been written to the FIFO which is also marked by DATA_OUTPUT_ENDOFPACKET(kept for optional usage).
	              writes_done <= '1;
				  write_pointer <= 0;
				end		
				else
				begin
	              // write pointer is incremented after every write to the FIFO
	              // when FIFO write signal is enabled.
	              write_pointer <= write_pointer + 1;
	              writes_done <= '0;	
				end
	          end
	      end  
	end

	// FIFO write enable generation
	assign fifo_wren = DATA_OUTPUT_VALID && avl_output_ready;

	// FIFO Implementation in FF's, infer FIFO in future
	reg  [DATA_WIDTH-1:0] stream_data_fifo [0 : NUMBER_OF_OUTPUT_WORDS-1];

	// Streaming input data is stored in FIFO
	always @( posedge M_AXIS_ACLK )
    begin
        if (fifo_wren)
            stream_data_fifo[write_pointer] <= DATA_OUTPUT_DATA;
	end		

	// Hook up axi-st tx signals
	//! data_input_ready indicates that the unit accepts transactions to read FIFO
	always@(posedge M_AXIS_ACLK or negedge M_AXIS_ARESETN) 
	begin
	  if(!M_AXIS_ARESETN)
	    begin
	      read_pointer <= 0;
		  reads_done <= '0;
		  M_AXIS_TVALID <= '0;
		  M_AXIS_TLAST <= '0;
	    end  
	  else if (read_pointer < NUMBER_OF_OUTPUT_WORDS-1)
	    begin
		  M_AXIS_TLAST <= '0;
		  reads_done <= '0;
		  if (fifo_almost_full)
			begin
			  read_pointer <= 0;
			  M_AXIS_TVALID <= '1;
			end
	      if (M_AXIS_TREADY && !reads_done)
	        begin
	          // read pointer is incremented after every read from the FIFO
	          // when M_AXIS_TREADY signal is enabled.
	          read_pointer <= read_pointer + 1;
	        end
		end			
	  else if (read_pointer == NUMBER_OF_OUTPUT_WORDS-1) // all data regardless
	    begin
	      // reads_done is asserted when NUMBER_OF_OUTPUT_WORDS numbers of streaming data 
	      // has been written to the FIFO which is also marked by M_AXIS_TLAST(kept for optional usage).
		  reads_done <= '1;
		  M_AXIS_TVALID <= '0;
		  M_AXIS_TLAST <= '1;
		  read_pointer <= 0;			  
	    end
	end

	
	// Data out
	assign M_AXIS_TDATA = stream_data_fifo[read_pointer][DATA_WIDTH-1:0];

	endmodule